tools:
  - class_name: "verl.tools.maths_tool.MathsAnswerTool"
    config:
      type: native
    tool_schema:
      type: "function"
      function:
        name: "calc_answer_reward"
        description: "A tool for calculating the reward of the answer to a maths question (1.0 if the parsed answer is correct, 0.0 if the parsed answer is incorrect or parsed incorrectly)."
        parameters:
          type: "object"
          properties:
            answer:
              type: "string"
              description: "The final answer to the math problem wrapped by \\boxed{}."
          required: ["answer"]