tools:
  - class_name: "verl.tools.sandbox_fusion_tools_auto.SandboxFusionTool"
    config: 
      sandbox_fusion_url: "http://10.206.0.184:8080/run_code"
      num_workers: 1
      enable_global_rate_limit: true
      rate_limit: 4
      default_timeout: 60
      default_language: "python"
      memory_limit_mb: 1024
      type: native

    tool_schema:
      type: "function"
      function:
        name: "code_interpreter"
        description: "A tool for executing code."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The code to execute."
          required: ["code"]