tools:
  - class_name: "verl.tools.browser_tools.BrowserTool"
    config: 
      mcp_url: "http://10.0.20.211:3000/mcp"
      type: native
    
    tool_schema:
      type: "function"
      function:
        name: "browser_tool"
        description: |-
          Tool to control the browser. You should pass two arguments: name (str) and params (dict).
          
          Available actions with name and params: 
          1. search_google_api(query: str, num_results: int=20): Search the query via Google api, the query should be like humans search keywords, concrete and not vague or super long.
          2. go_to_url(url: str): Navigate to URL in the current tab.
          3. go_back(): Navigate back.
          4. click_element(index: int): Click element by index.
          5. input_text(index: int, text: str): Input text into a input interactive element.
          6. switch_tab(page_id: int): Switch to the tab by page_id.
          7. open_tab(url: str): Open url in new tab.
          8. download_file(url: str, filename: str=None): Download file from a download link. "filename" will be extracted from the download link if not specified.
          
          Notes:
          1. The "index" param (e.g. in click_element) mean the index of **interactive elements** in the current webpage. You can only input visible index from webpage you see.
            e.g. In the page with content "[Start of page]\n[0]<a >新闻 />\n[1]<a >hao123 />\n[2]<a >地图 />\n[3]<a >贴吧 />...\n[20]<a >自贸试验区建设迈上新台阶 />\n[21]<li >热 />\n\t[22]<a >伊朗革命卫队总司令遇袭身亡 />\n[23]<li >热 />...", you can use `{"name": "click_element", "params": {"index": 20}}` to click the element (may be a link) corresponding to "自贸试验区建设迈上新台阶".
          2. Tool call format: `{"name": "action_name", "params": {"param1": value1, ...}}`.
        parameters:
          properties:
            name:
              enum:
              - search_google_api
              - go_to_url
              - go_back
              - click_element
              - input_text
              - switch_tab
              - open_tab
              - download_file
              # title: Name
              type: string
            params:
              additionalProperties: true
              type: object
              # title: Params
          required:
          - name
          - params
          # title: BrowserSchema
          type: object