tools:
  - class_name: "verl.tools.web_search_google.SearchGoogleTool"
    config:
      type: native
      
    tool_schema:
      type: "function"
      function:
        name: "search_google"
        description: "Search the query in Google in the current tab. The query should be concret, concise, and explicit."
        parameters:
          type: "object"
          properties:
            query:
              title: "Query"
              type: "string"
          required: ["query"]
          title: "search_google_args"

  - class_name: "verl.tools.web_go_to_url.GoToUrlTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "go_to_url"
        description: "Navigate to URL in the current tab"
        parameters:
          type: "object"
          properties:
            url:
              title: "Url"
              type: "string"
          required: ["url"]
          title: "go_to_url_args"

  - class_name: "verl.tools.web_go_back.GoBackTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "go_back"
        description: "Go back to the previous page in the browser."
        parameters:
          type: "object"
          properties: {}
          required: []
          title: "go_back_args"

  - class_name: "verl.tools.web_click_element.ClickElementTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "click_element"
        description: "Click on an element in the current tab."
        parameters:
          type: "object"
          properties:
            index:
              title: "Index"
              type: "integer"
          required: ["index"]
          title: "click_element_args"

  - class_name: "verl.tools.web_scroll_to_text.ScrollToTextTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "scroll_to_text"
        description: "If you dont find something which you want to interact with, scroll to it"
        parameters:
          type: "object"
          properties:
            text:
              title: "Text"
              type: "string"
          required: ["text"]
          title: "scroll_to_text_args"

  - class_name: "verl.tools.web_get_dropdown_options.GetDropdownOptionsTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "get_dropdown_options"
        description: "Get all options from a native dropdown"
        parameters:
          type: "object"
          properties:
            index:
              title: "Index"
              type: "integer"
          required: ["index"]
          title: "get_dropdown_options_args"

  - class_name: "verl.tools.web_select_dropdown_option.SelectDropdownOptionTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "select_dropdown_option"
        description: "Select dropdown option for interactive element index by the text of the option you want to select"
        parameters:
          type: "object"
          properties:
            index:
              title: "Index"
              type: "integer"
            text:
              title: "Text"
              type: "string"
          required: ["index", "text"]
          title: "select_dropdown_option_args"

  - class_name: "verl.tools.web_input_text.InputTextTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "input_text"
        description: "Input text into a input interactive element (e.g., search box)"
        parameters:
          type: "object"
          properties:
            index:
              title: "Index"
              type: "integer"
            text:
              title: "Text"
              type: "string"
            has_sensitive_data:
              title: "Has Sensitive Data"
              type: "boolean"
              default: false
          required: ["index", "text"]
          title: "input_text_args"

  - class_name: "verl.tools.web_switch_tab.SwitchTabTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "switch_tab"
        description: "Switch tab"
        parameters:
          type: "object"
          properties:
            page_id:
              title: "Page Id"
              type: "integer"
          required: ["page_id"]
          title: "switch_tab_args"

  - class_name: "verl.tools.web_open_tab.OpenTabTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "open_tab"
        description: "Open url in new tab"
        parameters:
          type: "object"
          properties:
            url:
              title: "Url"
              type: "string"
          required: ["url"]
          title: "open_tab_args"

  - class_name: "verl.tools.web_scroll_down.ScrollDownTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "scroll_down"
        description: "Scroll down the page by pixel amount - if no amount is specified, scroll down one page"
        parameters:
          type: "object"
          properties:
            amount:
              title: "Amount"
              type: "integer"
          required: []
          title: "scroll_down_args"

  - class_name: "verl.tools.web_scroll_up.ScrollUpTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "scroll_up"
        description: "Scroll up the page by pixel amount - if no amount is specified, scroll up one page"
        parameters:
          type: "object"
          properties:
            amount:
              title: "Amount"
              type: "integer"
          required: []
          title: "scroll_up_args"

  - class_name: "verl.tools.web_send_keys.SendKeysTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "send_keys"
        description: "Send strings of special keys like Escape,Backspace, Insert, PageDown, Delete, Enter, Shortcuts such as `Control+o`, `Control+Shift+T` are supported as well. This gets used in keyboard.press."
        parameters:
          type: "object"
          properties:
            keys:
              title: "Keys"
              type: "string"
          required: ["keys"]
          title: "send_keys_args"

  - class_name: "verl.tools.web_download_file.DownloadFileTool"
    config: {}
    tool_schema:
      type: "function"
      function:
        name: "download_file"
        description: "Download a file directly from the exact URL (download link)."
        parameters:
          type: "object"
          properties:
            url:
              title: "Url"
              type: "string"
              description: "The URL of the file to download."
            filename:
              title: "Filename"
              type: "string"
              description: "The name of the file to save. If not provided, the filename will be extracted from the URL."
              default: null
          required: ["url"]
          title: "download_file_args"
